# Generated by Django 4.1.3 on 2022-11-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'contents',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ibls_id', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(100, 'HTML текст'), (101, 'Текст'), (300, 'Аудио файл'), (401, 'Видео на Vimeo')])),
                ('data', models.JSONField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.content')),
            ],
            options={
                'db_table': 'materials',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=512)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='core.subject')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.lesson'),
        ),
    ]
